theme: jekyll-theme-minimal
title: <a href="https://github.com/cwolfbrandt/predicting_churn">Predicting User Churn</a> # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Comparison of Parametric and Non-Parametric Models
  <br>
  <br>
  <a href="https://cwolfbrandt.github.io">Return to Portfolio</a>
  <br>
theme: jekyll-theme-minimal

