theme: jekyll-theme-minimal
title: Predicting User Churn
description: > # your text below (remove <br> elements if you don't need line breaks)
  Comparison of Parametric and Non-Parametric Models
  <br>
  <br>
  <a href="https://cwolfbrandt.github.io">Return to Portfolio</a>
  <br>
theme: jekyll-theme-minimal

